### ISSUE TITLE
Docker image also for Raspberry Pi? 

### ISSUE THREAD

**Issue by garret** [carlonluca/docker-mldonkey#1]
Do you know how to get this image to also run on a Raspberry Pi (I have a 3B+)? 

Is this image the latest version of mldonkey (3.1.7)? 

Thank you in advance for your work.

**Comment by garret** [comment]
May I ask what should be the command for the raspberry pi 3? Sorry I am not very expert with docker.

**Comment by carlonluca** [comment]
The command to do what? There is no difference from any other Linux system from this point of view. Just start the container and you're done. You can find instructions in the readme in the repo.

**Comment by garret** [comment]
You are right, I managed to get it working on my Raspberry Pi 3B+. However, I have still some questions: 

1. I noticed that the admin password is not set up even though I specify it in the container option. This is the command I give: 
```
docker run --name=mldonkey \
              -i -t -d \
              -e MLDONKEY_ADMIN_PASSWORD=italia \
              -v "/mnt/media/mldonkey/:/var/lib/mldonkey" \
              -p 4080:4080 \
              -p 19040:19040 \
              -p 19044:19044 \
              --restart=unless-stopped \
			  carlonluca/mldonkey
```
I also cancelled the `/mnt/media/mldonkey/` folder to make sure there was no config setup. To fix the issue I changed the password through the web interface but would like to understand why it does not work from the container option. 

2. I could see in the container image that the ports `19040` and `19044` should be exposed. I assume these should be intended for the donkey network (TCP and UDP). However, these doors were not set for me for the donkey network (I had another random door) in the mldonkey config. I had to set `19040` manually through the web interface. Is that normal? 

3. Despite I port forwarded `19040` and `19044` on my router, they still result closed. I assume that is why I get low ID when I connect to donkey servers. Do you have any idea what I am doing wrong?  

Btw, another mistake I was doing was to use the `cheungpat/mldonkey` image and not yours because I just copied the docker command from your README (which is a fork of the `cheungpat` image). 

Thank you for the support.

**Comment by carlonluca** [comment]
1. You can test tag 3.1.7-2-test in docker hub.
2. I'm sorry, I don't exactly know where those ports come from. You can set ports in config files, map and forward.
3. I suppose the mldonkey binary provided by debian should support it. Experimental version 3.1.7-2 is built from sources, and Kademlia support was compiled in. You should try to enable it and see if it works.
