### ISSUE TITLE
Which ports are necessary?

### ISSUE THREAD

**Issue by wonx** [carlonluca/docker-mldonkey#10]
Hi,

I see that there's a pretty long list of ports, and you recommend exposing some of them to the host so it can be accessed. My question is, which ones are actually required? I'm curious about ports 4002 and 4003. Shouldn't the web interface for mldonkey-next communicate with the core inside the docker container?

**Comment by carlonluca** [comment]
Hello,
it is not possible for the WebApp to communicate with the mldonkey core directly. mldonkey just offers a TCP socket. So, port 4002 must be available to the WebApp.
Port 4003 is just used for the stream of logs: if you want that feature, the WebApp needs to connect to that port.

**Comment by wonx** [comment]
Thanks

**Comment by carlonluca** [comment]
No problem. Reopen if needed.
