### ISSUE TITLE
can init  can not create files in directory 

### ISSUE THREAD

**Issue by scascalesp** [carlonluca/docker-mldonkey#2]
Hello
su  docker run -i -t -e MLDONKEY_ADMIN_PASSWORD=xxxx -v "/mnt/data/Films:/var/lib/mldonkey" -e PUID=xxxx -e                                     PGID=xxx carlonluca/mldonkey

--
 Waiting for mldonkey to start...
2021/09/03 22:55:16 [cO] Starting MLDonkey 3.1.7.git ...
2021/09/03 22:55:16 [cO] Language EN, locale UTF-8, ulimit for open files 1024
2021/09/03 22:55:16 [cO] raised ulimit for open files from 1024 to 1048576
2021/09/03 22:55:16 [cO] MLDonkey is working in /var/lib/mldonkey

2021/09/03 22:55:16 [cO] creating new MLDonkey base directory in /var/lib/mldonkey

2021/09/03 22:55:16 can not create files in directory /var/lib/mldonkey, check rights...
/usr/lib/mldonkey/mldonkey_command: 15: /usr/lib/mldonkey/mldonkey_command: nc: not found
/usr/lib/mldonkey/mldonkey_command: 15: /usr/lib/mldonkey/mldonkey_command: nc: not found
/usr/lib/mldonkey/mldonkey_command: 15: /usr/lib/mldonkey/mldonkey_command: nc: not found
2021/09/03 22:55:20 [cO] Starting MLDonkey 3.1.7.git ...
2021/09/03 22:55:20 [cO] Language EN, locale UTF-8, ulimit for open files 1024
2021/09/03 22:55:20 [cO] raised ulimit for open files from 1024 to 1048576
2021/09/03 22:55:20 [cO] MLDonkey is working in /var/lib/mldonkey

2021/09/03 22:55:20 [cO] creating new MLDonkey base directory in /var/lib/mldonkey
2021/09/03 22:55:20 can not create files in directory /var/lib/mldonkey, check rights...

"/var/lib/mldonkey" is inside docker i supose and with -v can store in local path... or not?
thnks

**Comment by carlonluca** [comment]
Hello,
you can test this https://github.com/carlonluca/docker-mldonkey/commit/6e32fc49bb0d26bceb151c8fc2aec15cda1de151 to see if it fixes the problem.

**Comment by scascalesp** [comment]
Hello
what is it supposed to do? get last version? execute sh (i can't enter console)?

**Comment by carlonluca** [comment]
The command you entered is supposed to run the mldonkey service.
